// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: games.sql

package database

import (
	"context"
)

const createGame = `-- name: CreateGame :one
INSERT INTO
    games (created_at, updated_at, system_id, filename)
VALUES
    (?, ?, ?, ?) RETURNING id, created_at, updated_at, system_id, filename, md5_hash
`

type CreateGameParams struct {
	CreatedAt string
	UpdatedAt string
	SystemID  string
	Filename  string
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (Game, error) {
	row := q.db.QueryRowContext(ctx, createGame,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.SystemID,
		arg.Filename,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SystemID,
		&i.Filename,
		&i.Md5Hash,
	)
	return i, err
}
