// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
)

type Game struct {
	ID        int64
	CreatedAt string
	UpdatedAt string
	SystemID  string
	Filename  string
	Md5Hash   sql.NullString
}

type Safe struct {
	ID        int64
	CreatedAt string
	UpdatedAt string
	SystemID  string
	Filename  string
	Md5Hash   sql.NullString
}
